services:
  vela-chart:
    build: .
    container_name: vela-chart
    restart: unless-stopped
    environment:
      - PORT=3010
      - NODE_ENV=production
    mem_limit: 512m
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
